-- New Words
insert into public.words (word_en, category, difficulty) values
('Reebok','brands',3),
('Sudan','countries',1),
('dragon','animals',1),
('Halay','culture',2),
('Barack Obama','people',2),
('Kurdish music','culture',2),
('millennium','time',1),
('pig','animals',1),
('chef','professions',1),
('Audi','brands',3),
('boot','objects',1),
('driver','professions',1),
('chair','objects',1),
('Australia','countries',1),
('coconut','foods',1),
('present','objects',1),
('bottle','objects',1),
('Sherko Bekas','people',2),
('chocolate','foods',1),
('historian','professions',1),
('season','time',1),
('bag','objects',1),
('peace','concepts',2),
('Kendrick Lamar','people',2),
('Golden Gate Bridge','landmarks',3),
('Kurdish dance','culture',2),
('Mount Everest','landmarks',3),
('radio','objects',1),
('year','time',1),
('Tokyo','cities',1),
('Kawa','culture',2),
('farmer','professions',1),
('mustard','foods',1),
('equality','concepts',2),
('autumn','time',1),
('Leonardo da Vinci','people',2),
('Warsaw','cities',1),
('Kurdish literature','culture',2),
('winter','time',1),
('philosopher','professions',1),
('autonomy','concepts',2),
('Kurdish flag','culture',2),
('pear','foods',1),
('future','concepts',2),
('England','countries',1),
('beef','foods',1),
('meat','foods',1),
('spine','body',1),

('bartender','professions',1),
('BMW','brands',3),
('Beirut','cities',1),
('Masoud Barzani','people',2),
('sock','objects',1),
('chin','body',1),
('lawyer','professions',1),
('spoon','objects',1),
('photographer','professions',1),
('legend','concepts',2),
('fish','animals',1),
('rice','foods',1),
('toaster','objects',1),
('democracy','concepts',2),
('iron','objects',1),
('cream','foods',1),
('today','time',1),
('Ironman','characters',3),

('security guard','professions',1),
('toy','objects',1),
('hip','body',1),
('pillow','objects',1),
('Volleyball','sports',3),
('pink','colors',1),
('poet','professions',1),
('coffee','foods',1),
('hen','animals',1),
('hat','objects',1),
('seagull','animals',1),
('bed','objects',1),
('cyan','colors',1),
('Adidas','brands',3),
('giraffe','animals',1),
('neck','body',1),
('Airbnb','brands',3),
('mirror','objects',1),
('spinach','foods',1),
('gardener','professions',1),
('Dell','brands',3),
('writer','professions',1),
('cookie','foods',1),
('chili','foods',1),
('humanity','concepts',2),
('Tajikistan','countries',1),
('Great Wall of China','landmarks',3),
('Superman','characters',3),
('decade','time',1),
('muscle','body',1),
('skirt','objects',1),
('Snoop Dogg','people',2),
('rights','concepts',2),
('IBM','brands',3),
('Flash','characters',3),
('translator','professions',1),
('Google','brands',3),
('cabbage','foods',1),
('scientist','professions',1),
('champagne','foods',1),
('Netflix','brands',3),
('biologist','professions',1),
('Spain','countries',1),
('freezer','objects',1),
('Volkswagen','brands',3),
('Budapest','cities',1),
('Najmadin Faraj','people',2),
('Canada','countries',1),
('Turkey','countries',1),
('Japan','countries',1),
('camel','animals',1),
('Ramallah','cities',1),
('penguin','animals',1),
('tongue','body',1),
('Kamancheh','culture',2),
('swallow','animals',1),
('summer','time',1),
('brain','body',1),
('Statue of Liberty','landmarks',3),
('honey','foods',1),
('eyebrow','body',1),
('Saudi Arabia','countries',1),
('melon','foods',1),
('backpack','objects',1),
('Brazil','countries',1),
('mango','foods',1),
('head','body',1),
('Albert Einstein','people',2),
('salad','foods',1),
('Sony','brands',3),
('stomach','body',1),
('magazine','objects',1),
('Nvidia','brands',3),
('Adele','people',2),
('moment','time',1),
('Ocalan','culture',2),
('black','colors',1),
('ritual','concepts',2),
('cucumber','foods',1),
('Şivan Perwer','culture',2),
('notebook','objects',1),
('programmer','professions',1),
('ring','objects',1),
('Russia','countries',1),
('dance','concepts',2),
('lamp','objects',1),
('Green Lantern','characters',3),
('Snowboarding','sports',3),
('Afghanistan','countries',1),
('Qazi Muhammad','culture',2),
('Porsche','brands',3),
('Moscow','cities',1),
('Santiago','cities',1),
('plate','objects',1),
('professor','professions',1),
('brotherhood','concepts',2),
('tomorrow','time',1),
('shoe','objects',1),
('air conditioner','objects',1),
('solidarity','concepts',2),
('soybean','foods',1),
('burger','foods',1),
('education','concepts',2),
('Saz','culture',2),
('Diyarbakir','culture',2),
('Dubai','cities',1),
('Coca-Cola','brands',3),
('cake','foods',1),
('fruit','foods',1),
('walrus','animals',1),
('bat','animals',1),
('architect','professions',1),
('ankle','body',1),
('shoulder','body',1),
('hair','body',1),
('gin','foods',1),
('dog','animals',1),
('Joe Biden','people',2),
('coat','objects',1),
('lime','colors',1),
('Uber','brands',3),
('jacket','objects',1),
('liberation','concepts',2),
('tradition','concepts',2),
('olive','colors',1),
('Celadet Bedirxan','culture',2),
('Lebanon','countries',1),
('Judo','sports',3),
('minute','time',1),
('era','time',1),
('Celine Dion','people',2),
('peacock','animals',1),
('Charles Darwin','people',2),
('eyelash','body',1),
('century','time',1),
('Hakkari','culture',2),
('ruler','objects',1),
('ear','body',1),
('Tennis','sports',3),
('earrings','objects',1),
('car','objects',1),
('paper','objects',1),
('Puma','brands',3),
('Michael Jackson','people',2),
('Toronto','cities',1),
('Lisbon','cities',1),
('lips','body',1),
('Cigerxwin','culture',2),
('love','concepts',2),
('Elon Musk','people',2),
('prophecy','concepts',2),
('face','body',1),
('Jordan','countries',1),
('turquoise','colors',1),
('Deadpool','characters',3),
('goose','animals',1),
('Doha','cities',1),
('lobster','animals',1),
('tablet','objects',1),
('Los Angeles','cities',1),
('dress','objects',1),
('sacrifice','concepts',2),
('millisecond','time',1),
('clock','objects',1),
('freedom','concepts',2),
('rhino','animals',1),
('Soran','culture',2),
('papaya','foods',1),
('Fencing','sports',3),
('Cudi Mountain','landmarks',3),
('pencil','objects',1),
('Huawei','brands',3),
('hope','concepts',2),
('Mark Twain','people',2),
('liver','body',1),
('Qatar','countries',1),
('ketchup','foods',1),
('mouth','body',1),
('window','objects',1),
('pants','objects',1),
('resistance','concepts',2),
('goat','animals',1),
('Prague','cities',1),
('Spiderman','characters',3),
('São Paulo','cities',1),
('Petra','landmarks',3),
('eagle','animals',1),
('teeth','body',1),
('lemonade','foods',1),
('shrimp','animals',1),
('beer','foods',1),
('cabinet','objects',1),
('tomato','foods',1),
('Kaval','culture',2),
('sharpener','objects',1),
('toe','body',1),
('beige','colors',1),
('bus','objects',1),
('swan','animals',1),
('eggplant','foods',1),
('Niagara Falls','landmarks',3),
('pumpkin','foods',1),
('identity','concepts',2),
('Beyonce','people',2),
('phone','objects',1),
('Taj Mahal','landmarks',3),
('Hockey','sports',3),
('Angela Merkel','people',2),
('truck','objects',1),
('AMD','brands',3),
('plum','foods',1),
('interpreter','professions',1),
('Tehran','cities',1),
('belief','concepts',2),
('Damascus','cities',1),
('Captain America','characters',3),
('shirt','objects',1),
('vodka','foods',1),
('festival','concepts',2),
('nurse','professions',1),
('onion','foods',1),
('Iran','countries',1),
('LG','brands',3),
('Kazakhstan','countries',1),
('singer','professions',1),
('Mercedes','brands',3),
('Boxing','sports',3),
('milk','foods',1),
('ship','objects',1),
('corn','foods',1),
('James Joyce','people',2),
('Emily Dickinson','people',2),
('Madonna','people',2),
('Ottawa','cities',1),
('history','concepts',2),
('laptop','objects',1),
('newspaper','objects',1),
('noon','time',1),
('courage','concepts',2),
('culture','concepts',2),
('Pakistan','countries',1),
('pepper','foods',1),
('Newroz','culture',2),
('Mardin','culture',2),
('sisterhood','concepts',2),
('Bashur','culture',2),
('Rojhilat','culture',2),
('drawer','objects',1),
('Qamishli','culture',2),
('Kurdish language','culture',2),
('Algeria','countries',1),
('mechanic','professions',1),
('London','cities',1),
('Abraham Lincoln','people',2),
('Stephen King','people',2),
('Football','sports',3),
('Aquaman','characters',3),
('pasta','foods',1),
('table','objects',1),
('trainer','professions',1),
('China','countries',1),
('oven','objects',1),
('tea','foods',1),
('weekday','time',1),
('student','professions',1),
('Golf','sports',3),
('Madrid','cities',1),
('model','professions',1),
('Stonehenge','landmarks',3),
('Skiing','sports',3),
('firefighter','professions',1),
('Mustafa Barzani','people',2),
('brown','colors',1),
('coral','colors',1),
('hero','concepts',2),
('Sydney Opera House','landmarks',3),
('Kurdish food','culture',2),
('fox','animals',1),
('crab','animals',1),
('custom','concepts',2),
('Alexander Bell','people',2),
('pigeon','animals',1),
('Manama','cities',1),
('Uzbekistan','countries',1),
('author','professions',1),
('pilot','professions',1),
('Hulk','characters',3),
('New York','cities',1),
('door','objects',1),
('beans','foods',1),
('pancreas','body',1),
('therapist','professions',1),
('bicycle','objects',1),
('marker','objects',1),
('strawberry','foods',1),
('Amazon','brands',3),
('ginger','foods',1),
('cow','animals',1),
('Zurna','culture',2),
('Berlin','cities',1),
('weekend','time',1),
('chemist','professions',1),
('innovation','concepts',2),
('Eiffel Tower','landmarks',3),
('electrician','professions',1),
('Athens','cities',1),
('Seoul','cities',1),
('accountant','professions',1),
('knife','objects',1),
('Nikola Tesla','people',2),
('Wolverine','characters',3),
('Bakur','culture',2),
('Semane','culture',2),
('plane','objects',1),
('garlic','foods',1),
('director','professions',1),
('artist','professions',1),
('juice','foods',1),
('Taekwondo','sports',3),
('physicist','professions',1),
('water','foods',1),
('Basketball','sports',3),
('second','time',1),
('afternoon','time',1),
('Gymnastics','sports',3),
('faith','concepts',2),
('Rugby','sports',3),
('Mount Fuji','landmarks',3),
('white','colors',1),
































('salesperson','professions',1),
('Mount Damavand','landmarks',3),
('Mexico City','cities',1),
('motorcycle','objects',1),
('ball','objects',1),
('Twitter','brands',3),
('suitcase','objects',1),
('Amman','cities',1),
('kingfisher','animals',1),
('literature','concepts',2),
('finger','body',1),
('fashion designer','professions',1),
('J.R.R. Tolkien','people',2),
('ice cream','foods',1),
('Ferrari','brands',3),
('scarf','objects',1),
('soda','foods',1),
('Vienna','cities',1),
('pie','foods',1),
('rooster','animals',1),
('2Pac','people',2),
('Taylor Swift','people',2),
('skin','body',1),
('kidney','body',1),
('judge','professions',1),
('watermelon','foods',1),
('Jerusalem','cities',1),
('purple','colors',1),
('foot','body',1),
('Colosseum','landmarks',3),
('Galileo Galilei','people',2),
('Rihanna','people',2),
('actor','professions',1),
('Mastercard','brands',3),
('Angkor Wat','landmarks',3),
('Riyadh','cities',1),
('unity','concepts',2),
('Daf','culture',2),
('Toyota','brands',3),
('Sydney','cities',1),
('Pyramids of Giza','landmarks',3),
('spring','time',1),
('hawk','animals',1),
('Rojava','culture',2),
('Martin Luther King','people',2),
('Agatha Christie','people',2),
('Lima','cities',1),
('Shakira','people',2),
('silver','colors',1),
('USA','countries',1),
('dishwasher','objects',1),
('Ford','brands',3),
('shelf','objects',1),
('salt','foods',1),
('violet','colors',1),
('Sylvia Plath','people',2),
('Thor','characters',3),

('month','time',1),
('evening','time',1),
('vision','concepts',2),
('Batman','characters',3),
('Grand Canyon','landmarks',3),
('arm','body',1),
('Erbil','culture',2),
('Afrin','culture',2),
('wrist','body',1),
('hairdryer','objects',1),
('chicken','foods',1),
('rabbit','animals',1),
('nose','body',1),
('Barzani','culture',2),
('glove','objects',1),
('honor','concepts',2),
('India','countries',1),
('holiday','time',1),
('peas','foods',1),
('Leyla Zana','culture',2),
('desk','objects',1),
('technology','concepts',2),
('banker','professions',1),
('Zagros Mountains','landmarks',3),
('blueberry','foods',1),
('plumber','professions',1),
('computer','objects',1),
('bone','body',1),
('Iraq','countries',1),
('HP','brands',3),
('Libya','countries',1),
('banana','foods',1),
('Archery','sports',3),
('television','objects',1),
('Baghdad','cities',1),
('sparrow','animals',1),
('kiwi','foods',1),
('magenta','colors',1),
('martyr','concepts',2),
('Pepsi','brands',3),
('San Francisco','cities',1),
('nail','body',1),
('washing machine','objects',1),
('grape','foods',1),
('dolphin','animals',1),
('Ararat','landmarks',3),
('crow','animals',1),
('justice','concepts',2),
('koala','animals',1),
('Burj Khalifa','landmarks',3),
('Facebook','brands',3),
('doorbell','objects',1),
('Greece','countries',1),
('Bill Gates','people',2),
('astronomer','professions',1),
('shark','animals',1),
('gray','colors',1),
('Isaac Newton','people',2),
('bookcase','objects',1),
('Vladimir Putin','people',2),
('Bitlis','culture',2),
('Oman','countries',1),
('stove','objects',1),
('independence','concepts',2),
('midnight','time',1),
('leg','body',1),
('flamingo','animals',1),
('policeman','professions',1),
('duck','animals',1),
('Microsoft','brands',3),
('lung','body',1),
('Kobane','culture',2),
('Baseball','sports',3),
('bronze','colors',1),
('Mount Rushmore','landmarks',3),
('sunglasses','objects',1),
('Black Widow','characters',3),
('Eminem','people',2),
('turkey','animals',1),
('Ankara','cities',1),
('Peshmerga','culture',2),
('necklace','objects',1),
('rum','foods',1),
('rat','animals',1),
('back','body',1),
('Elvis Presley','people',2),
('journalist','professions',1),
('Big Ben','landmarks',3),
('janitor','professions',1),
('Yemen','countries',1),
('Oscar Wilde','people',2),
('editor','professions',1),
('Tower Bridge','landmarks',3),
('mouse','animals',1),
('card','objects',1),
('Joker','characters',3),
('fork','objects',1),
('William Shakespeare','people',2),
('bracelet','objects',1),
('Ada Lovelace','people',2),
('octopus','animals',1),
('sheep','animals',1),
('painter','professions',1),
('H.G. Wells','people',2),
('Paris','cities',1),
('sugar','foods',1),
('Nike','brands',3),
('Charles Dickens','people',2),
('Jay-Z','people',2),
('Sigmund Freud','people',2),
('train','objects',1),
('Kuwait','countries',1),
('Catwoman','characters',3),
('Bahrain','countries',1),
('camera','objects',1),
('YouTube','brands',3),
('Mahabad','culture',2),
('sculptor','professions',1),
('Melbourne','cities',1),
('Skating','sports',3),
('Lady Gaga','people',2),
('Kurdish Parliament','landmarks',3),
('owl','animals',1),
('chest','body',1),
('kangaroo','animals',1),
('raspberry','foods',1),
('sofa','objects',1),
('boat','objects',1),
('yogurt','foods',1),
('wolf','animals',1),
('Rome','cities',1),
('Karl Marx','people',2),
('revolution','concepts',2),
('Lenovo','brands',3),
('Morocco','countries',1),
('whiskey','foods',1),
('Nelson Mandela','people',2),
('Wonder Woman','characters',3),
('Biggie Smalls','people',2),
('otter','animals',1),
('Zakho','culture',2),
('science','concepts',2),
('Swimming','sports',3),
('parrot','animals',1),
('bear','animals',1),
('butter','foods',1),
('Cairo','cities',1),
('Syria','countries',1),
('Rowing','sports',3),
('game','objects',1),
('yellow','colors',1),
('Tanbur','culture',2),
('Mahatma Gandhi','people',2),
('France','countries',1),
('whale','animals',1),
('developer','professions',1),
('Razer','brands',3),
('hour','time',1),
('Newroz flag','culture',2),
('Samsung','brands',3),
('carrot','foods',1),
('Helsinki','cities',1),
('falcon','animals',1),
('PayPal','brands',3),
('pineapple','foods',1),
('heater','objects',1),
('gold','colors',1),
('Germany','countries',1),
('morning','time',1),
('war','concepts',2),
('language','concepts',2),
('wine','foods',1),
('Doctor Strange','characters',3),
('candy','foods',1),
('Kurdish clothing','culture',2),
('lifeguard','professions',1),
('gift','objects',1),
('Steve Jobs','people',2),
('light','objects',1),
('elbow','body',1),
('cup','objects',1),
('Slemani','culture',2),
('Tunisia','countries',1),
('microwave','objects',1),
('Acropolis','landmarks',3),
('yesterday','time',1),
('Jules Verne','people',2),
('Israel','countries',1),
('belt','objects',1),
('oil','foods',1),
('Florence Nightingale','people',2),
('Instagram','brands',3),
('elephant','animals',1),
('Egypt','countries',1),
('builder','professions',1),
('starfish','animals',1),
('pharmacist','professions',1),
('navy','colors',1),
('potato','foods',1),
('Kanye West','people',2),
('horse','animals',1),
('Visa','brands',3),
('carpenter','professions',1),
('dentist','professions',1),
('vegetable','foods',1),
('hippo','animals',1),
('Abdullah Ocalan','people',2),
('Kurdistan','culture',2),
('Karate','sports',3),
('fan','objects',1),
('Athletics','sports',3),
('woodpecker','animals',1),
('knee','body',1),
('Intel','brands',3),
('coach','professions',1),
('Cizre','culture',2),
('Uluru','landmarks',3),
('egg','foods',1),
('eraser','objects',1),
('watch','objects',1),
('Auckland','cities',1),
('vacuum','objects',1),
('music','concepts',2),
('Mark Zuckerberg','people',2),
('Kurdish culture','culture',2),
('lettuce','foods',1),
('Tesla','brands',3),
('Italy','countries',1),
('wallet','objects',1),
('couch','objects',1),
('blender','objects',1),
('glasses','objects',1),
('MMA','sports',3),
('pizza','foods',1),
('umbrella','objects',1),
('cherry','foods',1),
('Jane Austen','people',2),
('musician','professions',1),
('zebra','animals',1),
('George Orwell','people',2),
('periwinkle','colors',1),
('pork','foods',1),
('Kurdish poetry','culture',2),
('psychologist','professions',1),
('Halabja','culture',2),
('Istanbul','cities',1),
('squirrel','animals',1),
('Black Panther','characters',3),
('Qandil Mountains','landmarks',3);
































-- Translations
insert into public.word_translations (word_en, lang, term) values
('Reebok','krd','Reebok'),
('Sudan','krd','Sûdan'),
('dragon','krd','Ejdeha'),
('Halay','krd','Govend'),
('Barack Obama','krd','Barack Obama'),
('Kurdish music','krd','Muzîka kurdî'),
('millennium','krd','Hezarsal'),
('pig','krd','Beraz'),
('chef','krd','Serkar / Chef'),
('Audi','krd','Audi'),
('boot','krd','Qayîk'),
('driver','krd','Ajovan'),
('chair','krd','Rûniştok / Kursî'),
('Australia','krd','Awistralya'),
('coconut','krd','Giwêza hindê'),
('present','krd','Diyarî'),
('bottle','krd','Şûşe'),
('chocolate','krd','çîkolata'),
('historian','krd','dîrokzan'),
('season','krd','demsal'),
('bag','krd','tûr'),
('peace','krd','aşîtî'),
('Kurdish dance','krd','Govend'),
('Mount Everest','krd','Çiyayê Everestê'),
('radio','krd','radyo'),
('year','krd','sal'),
('Tokyo','krd','Tokyo'),
('Kawa','krd','Kawa'),
('farmer','krd','gûndî'),
('mustard','krd','xerdel'),
('equality','krd','wekhevî'),
('autumn','krd','payiz'),
('Leonardo da Vinci','krd','Leonardo da Vinci'),
('Warsaw','krd','Warsaw'),
('literature','krd','hêdane / Edeb'),
('winter','krd','zivistan'),
('fish','krd','masî'),
('philosopher','krd','fîlozof'),
('autonomy','krd','xweserî'),
('Kurdish flag','krd','Ala Rengîn'),
('pear','krd','hirmî'),
('future','krd','pêşeroj'),
('England','krd','Îngilîstan'),
('beef','krd','goştê dewêr'),
('meat','krd','goşt'),
('spine','krd','movik'),

('bartender','krd','karkerê barê'),
('BMW','krd','BMW'),
('Beirut','krd','Beyrut'),
('Masoud Barzani','krd','Masoud Barzani'),
('sock','krd','Gore'),
('chin','krd','Zenî'),
('lawyer','krd','parêzkar'),
('spoon','krd','kevçî'),
('photographer','krd','wênekêş'),
('legend','krd','Destan / legend'),
('rice','krd','birinc'),
('toaster','krd','tosbirajt'),
('democracy','krd','dimûqratî'),
('iron','krd','Rêzer / iron'),
('cream','krd','qeymax'),
('today','krd','îro'),
('Ironman','krd','Ironman'),
('Najmadin Faraj','krd','Najmadin Faraj'),
('security guard','krd','bedenparêz'),
('toy','krd','lîstok'),
('hip','krd','bêjin'),
('pillow','krd','balîf / Balgih'),
('Volleyball','krd','Volîbal'),
('pink','krd','pembe'),
('poet','krd','Helbestvan'),
('Cigerxwin','krd','Cigerxwin'),
('coffee','krd','qehwe'),
('hen','krd','mirîşk'),
('hat','krd','kûm'),
('seagull','krd','teyrav'),
('bed','krd','nivîn'),
('cyan','krd','turkuaz'),
('Adidas','krd','Adidas'),
('giraffe','krd','Pîşîş'),
('neck','krd','gerden / qirrik / Sukur'),
('Airbnb','krd','Airbnb'),
('mirror','krd','neynik'),
('spinach','krd','spînak'),
('gardener','krd','baxçevan'),
('Dell','krd','Dell'),
('writer','krd','nivîskar'),
('cookie','krd','Sewik'),
('chili','krd','Bîber'),
('humanity','krd','mirovatî'),
('Tajikistan','krd','Tajikistan'),
('Great Wall of China','krd','Sûrê Mezin ê Çînê'),
('Superman','krd','Superman'),
('decade','krd','dehsal'),
('muscle','krd','masûl'),
('skirt','krd','pôşak / Çepûn'),
('Snoop Dogg','krd','Snoop Dogg'),
('rights','krd','maf'),
('IBM','krd','IBM'),
('Flash','krd','Birûsk'),
('translator','krd','Ferheng'),
('Google','krd','Google'),
('cabbage','krd','lihane'),
('scientist','krd','zanistvan'),
('champagne','krd','şampanya'),
('Netflix','krd','Netflix'),
('biologist','krd','jîyanzan'),
('Spain','krd','Îspanya'),
('freezer','krd','dolab / berade'),
('Volkswagen','krd','Volkswagen'),
('Budapest','krd','Budapest'),
('Canada','krd','Canada'),
('Turkey','krd','Tirkî'),
('Japan','krd','Japonya'),
('camel','krd','deveh'),
('Ramallah','krd','Ramallah'),
('penguin','krd','pengûwîn'),
('tongue','krd','ziman'),
('Kamancheh','krd','Kamançe'),
('swallow','krd','qurtandin'),
('summer','krd','havîn'),
('brain','krd','mejî'),
('Statue of Liberty','krd','Peykerê Azadiyê'),
('honey','krd','hingiv'),
('eyebrow','krd','birû'),
('Saudi Arabia','krd','Erebistana Suûdî'),
('melon','krd','petêx'),
('backpack','krd','turê piştê'),
('Brazil','krd','Brezîlya'),
('mango','krd','mango'),
('head','krd','ser'),
('Albert Einstein','krd','Albert Einstein'),
('salad','krd','xas'),
('Sony','krd','Sony'),
('stomach','krd','made'),
('magazine','krd','rojname'),
('Nvidia','krd','Nvidia'),
('Adele','krd','Adele'),
('moment','krd','kêlîk'),
('Ocalan','krd','Ocalan'),
('black','krd','reş'),
('ritual','krd','awa'),
('cucumber','krd','xiyar'),
('Şivan Perwer','krd','Şivan Perwer'),
('notebook','krd','laptop'),
('programmer','krd','bernamenûs / programmer'),
('ring','krd','hungilîsk'),
('Russia','krd','Rûsya'),
('dance','krd','dîlan'),
('lamp','krd','çira'),
('Green Lantern','krd','çira kesk'),
('Snowboarding','krd','Snowboarding'),
('Afghanistan','krd','Afxanistan'),
('Qazi Muhammad','krd','Qazi Muhammad'),
('Porsche','krd','Porsche'),
('Moscow','krd','Moskow'),
('Santiago','krd','Santiago'),
('plate','krd','lalîk / sînîk'),
('professor','krd','profesor'),
('brotherhood','krd','biratî'),
('tomorrow','krd','sibê'),
('shoe','krd','pêlav'),
('air conditioner','krd','klîma'),
('solidarity','krd','hevgirtin'),
('soybean','krd','soya'),
('burger','krd','burger'),
('education','krd','zanyarî'),
('Saz','krd','Tembûr'),
('Diyarbakir','krd','Amed'),
('Dubai','krd','Dubai'),
('Coca-Cola','krd','Coca-Cola'),
('cake','krd','gato'),
('fruit','krd','fêkî'),
('walrus','krd','hespê derya / walrus'),
('bat','krd','Cil'),
('architect','krd','mîmar / architect'),
('ankle','krd','gûzek'),
('shoulder','krd','mil'),
('hair','krd','por'),
('gin','krd','gin'),
('dog','krd','se / Kûçik'),
('Joe Biden','krd','Joe Biden'),
('coat','krd','qaput'),
('lime','krd','lîmon'),
('Uber','krd','Uber'),
('jacket','krd','jacket / sako'),
('liberation','krd','rizgarî'),
('tradition','krd','kevneşopî'),
('olive','krd','zeytûn'),
('Celadet Bedirxan','krd','Celadet Bedirxan'),
('Lebanon','krd','Lubnan'),
('Judo','krd','Judo'),
('minute','krd','xulek'),
('era','krd','serdem'),
('Celine Dion','krd','Celine Dion'),
('peacock','krd','teyrê tawûs'),
('Charles Darwin','krd','Charles Darwin'),
('eyelash','krd','mûçav / Mûjgul'),
('century','krd','sedsal'),
('Hakkari','krd','Hakkari'),
('ruler','krd','padîşah / hukumdar'),
('ear','krd','guh'),
('Tennis','krd','Tênnis'),
('earrings','krd','guhar'),
('car','krd','trimbêl / Otomobîl'),
('paper','krd','kaxez'),
('Puma','krd','Puma'),
('Michael Jackson','krd','Michael Jackson'),
('Toronto','krd','Toronto'),
('Lisbon','krd','Lisbon'),
('lips','krd','lêv'),
('love','krd','evîn'),
('Elon Musk','krd','Elon Musk'),
('prophecy','krd','pêxemberîtî'),
('face','krd','rû'),
('Jordan','krd','Urdun'),
('turquoise','krd','turkuaz'),
('Deadpool','krd','Deadpool'),
('goose','krd','qaz'),
('Doha','krd','Doha'),
('lobster','krd','kevcal'),
('tablet','krd','tablet'),
('Los Angeles','krd','Los Angeles'),
('dress','krd','kiras'),
('sacrifice','krd','fedakari'),
('millisecond','krd','mîlîsanîye'),
('clock','krd','demjimêr'),
('freedom','krd','azadî'),
('rhino','krd','kerkedan'),
('Soran','krd','Soran'),
('papaya','krd','papaya'),
('Fencing','krd','Fencing'),
('Cudi Mountain','krd','Çiyayê Cûdî'),
('pencil','krd','pênûs'),
('Huawei','krd','Huawei'),
('hope','krd','hêvî'),
('Mark Twain','krd','Mark Twain'),
('liver','krd','ceger'),
('Qatar','krd','Qatar'),
('ketchup','krd','ava bacanê sor'),
('mouth','krd','dev'),
('window','krd','pace / pencere'),
('pants','krd','pantol'),
('resistance','krd','berxwedan'),
('goat','krd','bizin'),
('Prague','krd','Prague'),
('Spiderman','krd','Spiderman'),
('São Paulo','krd','São Paulo'),
('Petra','krd','Petra'),
('eagle','krd','qertel / nisir'),
('teeth','krd','diran'),
('lemonade','krd','ava leymûnê'),
('shrimp','krd','kevcal'),
('beer','krd','bîra'),
('cabinet','krd','dolab'),
('tomato','krd','bacanê sor'),
('Kaval','krd','Kaval'),
('sharpener','krd','tûjker'),
('toe','krd','tilîyê pê'),
('beige','krd','bej'),
('bus','krd','bas'),
('swan','krd','qazê spî'),
('eggplant','krd','bacanê reş'),
('Niagara Falls','krd','Niagara Falls'),
('pumpkin','krd','kûndir'),
('identity','krd','nasname'),
('Beyonce','krd','Beyonce'),
('phone','krd','telefon'),
('Taj Mahal','krd','Taj Mahal'),
('Hockey','krd','Hockey'),
('Angela Merkel','krd','Angela Merkel'),
('truck','krd','kamyon'),
('AMD','krd','AMD'),
('plum','krd','alûc'),
('interpreter','krd','werger'),
('Tehran','krd','Tehran'),
('belief','krd','bawerî'),
('Damascus','krd','Şam'),
('Captain America','krd','Captain America'),
('shirt','krd','gomlek'),
('vodka','krd','vodka'),
('festival','krd','cejn'),
('nurse','krd','nexweşyare'),
('onion','krd','pîvaz'),
('Iran','krd','Iran'),
('LG','krd','LG'),
('Kazakhstan','krd','Kazakhstan'),
('singer','krd','stranbêj'),
('Mercedes','krd','Mercedes'),
('Boxing','krd','Boxing'),
('milk','krd','şîr'),
('ship','krd','gemî / keştî'),
('corn','krd','garis'),
('James Joyce','krd','James Joyce'),
('Emily Dickinson','krd','Emily Dickinson'),
('Madonna','krd','Madonna'),
('Ottawa','krd','Ottawa'),
('history','krd','dîrok'),
('laptop','krd','laptop'),
('newspaper','krd','rojname'),
('noon','krd','nîvroj'),
('courage','krd','qehremanî'),
('culture','krd','çand'),
('Pakistan','krd','Pakistan'),
('pepper','krd','îsota reş'),
('Newroz','krd','Newroz'),
('Mardin','krd','Mardin'),
('sisterhood','krd','xwişk'),
('Bashur','krd','başûr'),
('Rojhilat','krd','Rojhilat'),
('drawer','krd','berkêşk'),
('Qamishli','krd','Qamişlo'),

('Kurdish language','krd','Zimanê Kurdî'),
('Algeria','krd','Cezayîr'),
('mechanic','krd','mekanîk'),
('London','krd','London'),
('Abraham Lincoln','krd','Abraham Lincoln'),
('Stephen King','krd','Stephen King'),
('Football','krd','futbol'),
('Aquaman','krd','Aquaman'),
('pasta','krd','makaron'),
('table','krd','masê'),
('trainer','krd','fêrker'),
('China','krd','çîn'),
('oven','krd','tenûr'),
('tea','krd','çay'),
('weekday','krd','roja hefteyê'),
('student','krd','xwendekar'),
('Golf','krd','Golf'),
('Madrid','krd','Madrid'),
('model','krd','şêwaz'),
('Stonehenge','krd','Stonehenge'),
('Skiing','krd','befirajotin'),
('firefighter','krd','agirkuj'),
('Mustafa Barzani','krd','Mustafa Barzani'),
('brown','krd','qehweyî'),
('coral','krd','koral'),
('hero','krd','qehreman'),
('Sydney Opera House','krd','Sydney Opera House'),
('Kurdish food','krd','Xwarina kurdî'),
('fox','krd','rovî'),
('crab','krd','kevcal'),
('custom','krd','taybetî'),
('Alexander Bell','krd','Alexander Bell'),
('pigeon','krd','kevok'),
('Manama','krd','Manama'),
('Uzbekistan','krd','Uzbekistan'),
('author','krd','nivîskar'),
('pilot','krd','pîlot'),
('Hulk','krd','Hulk'),
('New York','krd','New York'),
('door','krd','derî'),
('beans','krd','fasûlî'),
('pancreas','krd','pankreasê'),
('therapist','krd','terapîst'),
('bicycle','krd','bisîklêt'),
('marker','krd','nîşanker'),
('strawberry','krd','erdtû'),
('Amazon','krd','Amazon'),
('ginger','krd','zencebîl'),
('cow','krd','çêlek'),
('Zurna','krd','Zurna'),
('Berlin','krd','Berlin'),
('weekend','krd','dawîaya heftê'),
('chemist','krd','kimyager'),
('innovation','krd','nûkirin'),
('Eiffel Tower','krd','Birca Eyfel'),
('electrician','krd','elektrîker'),
('Athens','krd','Athens'),
('Seoul','krd','Seoul'),
('accountant','krd','hejmarvan'),
('knife','krd','kêr'),
('Nikola Tesla','krd','Nikola Tesla'),
('Wolverine','krd','Wolverine'),
('Bakur','krd','Bakur'),
('Semane','krd','Semane'),
('plane','krd','balafir'),
('garlic','krd','sîr'),
('director','krd','serok'),
('artist','krd','Hunermend'),
('juice','krd','ava fêkî'),
('Taekwondo','krd','Taekwondo'),
('physicist','krd','fîzîknas'),
('water','krd','av'),
('Basketball','krd','Basketball'),
('second','krd','sanîye'),
('afternoon','krd','piştînîvroj'),
('Gymnastics','krd','Bedenparêzî / Gymnastics'),
('faith','krd','bawerî'),
('Rugby','krd','Rugby'),
('Mount Fuji','krd','Çiyayê Fuji'),
('white','krd','spî'),




























('salesperson','krd','salesperson'),
('Mount Damavand','krd','Mount Damavand'),
('Mexico City','krd','Mexico City'),
('motorcycle','krd','motorcycle'),
('ball','krd','ball'),
('Twitter','krd','Twitter'),
('suitcase','krd','suitcase'),
('Amman','krd','Amman'),
('kingfisher','krd','kingfisher'),
('literature','krd','edebiyat'),
('finger','krd','pênc'),
('fashion designer','krd','fashion designer'),
('J.R.R. Tolkien','krd','J.R.R. Tolkien'),
('ice cream','krd','ice cream'),
('Ferrari','krd','Ferrari'),
('scarf','krd','scarf'),
('soda','krd','soda'),
('Vienna','krd','Vienna'),
('pie','krd','pie'),
('rooster','krd','rooster'),
('2Pac','krd','2Pac'),
('Taylor Swift','krd','Taylor Swift'),
('skin','krd','cil'),
('kidney','krd','gurçik'),
('judge','krd','judge'),
('watermelon','krd','watermelon'),
('Jerusalem','krd','Jerusalem'),
('purple','krd','mor'),
('foot','krd','pê'),
('Colosseum','krd','Colosseum'),
('Galileo Galilei','krd','Galileo Galilei'),
('Rihanna','krd','Rihanna'),
('actor','krd','actor'),
('Mastercard','krd','Mastercard'),
('Angkor Wat','krd','Angkor Wat'),
('Riyadh','krd','Riyadh'),
('unity','krd','yekîtî'),
('Daf','krd','Daf'),
('Toyota','krd','Toyota'),
('Sydney','krd','Sydney'),
('Pyramids of Giza','krd','Pyramids of Giza'),
('spring','krd','spring'),
('hawk','krd','hawk'),
('Rojava','krd','Rojava'),
('Martin Luther King','krd','Martin Luther King'),
('Agatha Christie','krd','Agatha Christie'),
('Lima','krd','Lima'),
('Shakira','krd','Shakira'),
('silver','krd','zîvî'),
('USA','krd','USA'),
('dishwasher','krd','dishwasher'),
('Ford','krd','Ford'),
('shelf','krd','shelf'),
('salt','krd','salt'),
('violet','krd','mora'),
('Sylvia Plath','krd','Sylvia Plath'),
('Thor','krd','Thor'),

('month','krd','month'),
('evening','krd','evening'),
('vision','krd','dîtin'),
('Batman','krd','Batman'),
('Grand Canyon','krd','Grand Canyon'),
('arm','krd','bazû'),
('Erbil','krd','Erbil'),
('Afrin','krd','Afrin'),
('wrist','krd','külle'),
('hairdryer','krd','hairdryer'),
('chicken','krd','chicken'),
('rabbit','krd','rabbit'),
('nose','krd','poz'),
('Barzani','krd','Barzani'),
('glove','krd','glove'),
('honor','krd','rûmeta'),
('India','krd','India'),
('holiday','krd','holiday'),
('peas','krd','peas'),
('Leyla Zana','krd','Leyla Zana'),
('desk','krd','desk'),
('technology','krd','teknolojî'),
('banker','krd','banker'),
('Zagros Mountains','krd','Zagros Mountains'),
('blueberry','krd','blueberry'),
('plumber','krd','plumber'),
('computer','krd','computer'),
('bone','krd','eskelet'),
('Iraq','krd','Iraq'),
('HP','krd','HP'),
('Libya','krd','Libya'),
('banana','krd','banana'),
('Archery','krd','Archery'),
('television','krd','television'),
('Baghdad','krd','Baghdad'),
('sparrow','krd','sparrow'),
('kiwi','krd','kiwi'),
('magenta','krd','magenta'),
('martyr','krd','şehîd'),
('Pepsi','krd','Pepsi'),
('San Francisco','krd','San Francisco'),
('nail','krd','diran'),
('washing machine','krd','washing machine'),
('grape','krd','grape'),
('dolphin','krd','dolphin'),
('Ararat','krd','Ararat'),
('crow','krd','crow'),
('justice','krd','edalet'),
('koala','krd','koala'),
('Burj Khalifa','krd','Burj Khalifa'),
('Facebook','krd','Facebook'),
('doorbell','krd','doorbell'),
('Greece','krd','Greece'),
('Bill Gates','krd','Bill Gates'),
('astronomer','krd','astronomer'),
('shark','krd','shark'),
('gray','krd','şevîn'),
('Isaac Newton','krd','Isaac Newton'),
('bookcase','krd','bookcase'),
('Vladimir Putin','krd','Vladimir Putin'),
('Bitlis','krd','Bitlis'),
('Oman','krd','Oman'),
('stove','krd','stove'),
('independence','krd','serxwebûn'),
('midnight','krd','midnight'),
('leg','krd','qet'),
('flamingo','krd','flamingo'),
('policeman','krd','policeman'),
('duck','krd','duck'),
('Microsoft','krd','Microsoft'),
('lung','krd','pist'),
('Kobane','krd','Kobane'),
('Baseball','krd','Baseball'),
('bronze','krd','bronze'),
('Mount Rushmore','krd','Mount Rushmore'),
('sunglasses','krd','sunglasses'),
('Black Widow','krd','Black Widow'),
('Eminem','krd','Eminem'),
('turkey','krd','turkey'),
('Ankara','krd','Ankara'),
('Peshmerga','krd','Peshmerga'),
('necklace','krd','necklace'),
('rum','krd','rum'),
('rat','krd','rat'),
('back','krd','pişt'),
('Elvis Presley','krd','Elvis Presley'),
('journalist','krd','journalist'),
('Big Ben','krd','Big Ben'),
('janitor','krd','janitor'),
('Yemen','krd','Yemen'),
('Oscar Wilde','krd','Oscar Wilde'),
('editor','krd','editor'),
('Tower Bridge','krd','Tower Bridge'),
('mouse','krd','mouse'),
('card','krd','card'),
('Joker','krd','Joker'),
('fork','krd','fork'),
('William Shakespeare','krd','William Shakespeare'),
('bracelet','krd','bracelet'),
('Ada Lovelace','krd','Ada Lovelace'),
('octopus','krd','octopus'),
('sheep','krd','biz'),
('painter','krd','painter'),
('H.G. Wells','krd','H.G. Wells'),
('Paris','krd','Paris'),
('sugar','krd','sugar'),
('Nike','krd','Nike'),
('Charles Dickens','krd','Charles Dickens'),
('Jay-Z','krd','Jay-Z'),
('Sigmund Freud','krd','Sigmund Freud'),
('train','krd','train'),
('Kuwait','krd','Kuwait'),
('Catwoman','krd','Catwoman'),
('Bahrain','krd','Bahrain'),
('camera','krd','camera'),
('YouTube','krd','YouTube'),
('Mahabad','krd','Mahabad'),
('sculptor','krd','sculptor'),
('Melbourne','krd','Melbourne'),
('Skating','krd','Skating'),
('Lady Gaga','krd','Lady Gaga'),
('Kurdish Parliament','krd','Kurdish Parliament'),
('owl','krd','owl'),
('chest','krd','sin'),
('kangaroo','krd','kangaroo'),
('raspberry','krd','raspberry'),
('sofa','krd','sofa'),
('boat','krd','boat'),
('yogurt','krd','yogurt'),
('wolf','krd','wolf'),
('Rome','krd','Rome'),
('Karl Marx','krd','Karl Marx'),
('revolution','krd','şoreş'),
('Lenovo','krd','Lenovo'),
('Morocco','krd','Morocco'),
('whiskey','krd','whiskey'),
('Nelson Mandela','krd','Nelson Mandela'),
('Wonder Woman','krd','Wonder Woman'),
('Biggie Smalls','krd','Biggie Smalls'),
('otter','krd','otter'),
('Zakho','krd','Zakho'),
('science','krd','zanist'),
('Swimming','krd','Swimming'),
('parrot','krd','parrot'),
('bear','krd','hês'),
('butter','krd','butter'),
('Cairo','krd','Cairo'),
('Syria','krd','Syria'),
('Rowing','krd','Rowing'),
('game','krd','game'),
('yellow','krd','zer'),
('Tanbur','krd','Tanbur'),
('Mahatma Gandhi','krd','Mahatma Gandhi'),
('France','krd','France'),
('whale','krd','whale'),
('developer','krd','developer'),
('Razer','krd','Razer'),
('hour','krd','hour'),
('Newroz flag','krd','Newroz flag'),
('Samsung','krd','Samsung'),
('carrot','krd','carrot'),
('Helsinki','krd','Helsinki'),
('falcon','krd','falcon'),
('PayPal','krd','PayPal'),
('pineapple','krd','pineapple'),
('heater','krd','heater'),
('gold','krd','zerî'),
('Germany','krd','Germany'),
('morning','krd','morning'),
('war','krd','şer'),
('language','krd','ziman'),
('wine','krd','wine'),
('Doctor Strange','krd','Doctor Strange'),
('candy','krd','candy'),
('Kurdish clothing','krd','Kurdish clothing'),
('lifeguard','krd','lifeguard'),
('gift','krd','gift'),
('Steve Jobs','krd','Steve Jobs'),
('light','krd','light'),
('elbow','krd','zêde'),
('cup','krd','cup'),
('Slemani','krd','Slemani'),
('Tunisia','krd','Tunisia'),
('microwave','krd','microwave'),
('Acropolis','krd','Acropolis'),
('yesterday','krd','yesterday'),
('Jules Verne','krd','Jules Verne'),
('Israel','krd','Israel'),
('belt','krd','belt'),
('oil','krd','oil'),
('Florence Nightingale','krd','Florence Nightingale'),
('Instagram','krd','Instagram'),
('elephant','krd','elephant'),
('Egypt','krd','Egypt'),
('builder','krd','builder'),
('starfish','krd','starfish'),
('pharmacist','krd','pharmacist'),
('navy','krd','naviyê'),
('potato','krd','potato'),
('Kanye West','krd','Kanye West'),
('horse','krd','hesp'),
('Visa','krd','Visa'),
('carpenter','krd','carpenter'),
('dentist','krd','dentist'),
('vegetable','krd','vegetable'),
('hippo','krd','hippo'),
('Abdullah Ocalan','krd','Abdullah Ocalan'),
('Kurdistan','krd','Kurdistan'),
('Karate','krd','Karate'),
('fan','krd','fan'),
('Athletics','krd','Athletics'),
('woodpecker','krd','woodpecker'),
('knee','krd','gûnişk'),
('Intel','krd','Intel'),
('coach','krd','coach'),
('Cizre','krd','Cizre'),
('Uluru','krd','Uluru'),
('egg','krd','egg'),
('eraser','krd','eraser'),
('watch','krd','watch'),
('Auckland','krd','Auckland'),
('vacuum','krd','vacuum'),
('music','krd','muzîk'),
('Mark Zuckerberg','krd','Mark Zuckerberg'),
('Kurdish culture','krd','Kurdish culture'),
('lettuce','krd','lettuce'),
('Tesla','krd','Tesla'),
('Italy','krd','Italy'),
('wallet','krd','wallet'),
('couch','krd','couch'),
('blender','krd','blender'),
('glasses','krd','glasses'),
('MMA','krd','MMA'),
('pizza','krd','pizza'),
('umbrella','krd','umbrella'),
('cherry','krd','cherry'),
('Jane Austen','krd','Jane Austen'),
('musician','krd','musician'),
('zebra','krd','zebra'),
('George Orwell','krd','George Orwell'),
('periwinkle','krd','perivînkul'),
('pork','krd','pork'),
('Kurdish poetry','krd','Kurdish poetry'),
('psychologist','krd','psychologist'),
('Halabja','krd','Halabja'),
('Istanbul','krd','Istanbul'),
('squirrel','krd','squirrel'),
('Black Panther','krd','Black Panther'),
('Qandil Mountains','krd','Qandil Mountains');
